title: "Ramblings of a student failing at life"
author: "Your Name"
email: mitrashuvraneel@gmail.com
description: >-
  Notes, ideas, and detailed explanations of programming problems â€” written in Markdown.
theme: minima
show_excerpts: true

markdown: kramdown
highlighter: rouge

github_username: ShuvraneelMitra
linkedin_username: https://www.linkedin.com/in/shuvraneelmitra/
