title: "Ramblings of a Student Failing at Life"
author: "Shuvraneel"
email: "mitrashuvraneel@gmail.com"
description: >-
  A collection of my thoughts, experiments, and failures.
theme: jekyll-theme-midnight

show_excerpts: true

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge

github_username: ShuvraneelMitra
linkedin_username: shuvraneelmitra

collections:
  posts:
    output: true
    permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
