title: "Ramblings of a student failing at life"
author: "Your Name"
email: mitrashuvraneel@gmail.com
description: >- 
theme: minima
show_excerpts: true

markdown: kramdown
highlighter: rouge

github_username: ShuvraneelMitra
linkedin_username: https://www.linkedin.com/in/shuvraneelmitra/

minima:
  nav:
    - title: "Home"
      url: /
    - title: "Problems"
      url: /problems/
    - title: "About"
      url: /about/