title: "Ramblings of a student failing at life"
author: "Shuvraneel"
email: mitrashuvraneel@gmail.com
description: >-
  Thoughts, frustrations, and code snippets from a student still figuring things out.
theme: jekyll-theme-midnight

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /:categories/:title/

menu:
  - title: Home
    url: /
  - title: Categories
    url: /categories/

paginate: 5
paginate_path: /page:num/

markdown: kramdown
highlighter: rouge

github_username: ShuvraneelMitra
linkedin_username: shuvraneelmitra
