title: "Ramblings of a student failing at life"
author: "Shuvraneel"
email: mitrashuvraneel@gmail.com
description: >- 
theme: jekyll-theme-chirpy
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /:categories/:title/

menu:
  - title: Home
    url: /
  - title: Problem-Solving
    url: /programming/

paginate: 5
paginate_path: /page:num/

markdown: kramdown
highlighter: rouge

github_username: ShuvraneelMitra
linkedin_username: shuvraneelmitra